<?php
define('Root_Path',dirname(__FILE__));
define('Project_Folder_Name',"/LLSystem");
define('Site_Name','兄弟门户');
define('Site_Version','Ver-1.1');
//前台html用
define('Product_Img',"./admin/images/product/");
define('Slider_Img',"./resource/slider/");
define('News_Thumb',"./resource/newsThumb/");
define('News_File',"./resource/newsFile/");
define('News_Page_Size',6);
define('Productsall_Thumb',"./resource/productsallThumb/");
define('Productsall_File',"./resource/productsallFile/");
//admin html用
define('Admin_Slider_Img',"../resource/slider/");
//后端php用
define('Type4Product',2);
define('PHP_Product_Img_Path',Root_Path."/admin/images/product/");
define('PHP_Slider_Img',Root_Path."/resource/slider/");
define('PHP_News_Thumb',Root_Path."/resource/newsThumb/");
define('PHP_News_File',Root_Path."/resource/newsFile/");
define('PHP_News_UM_Img',"../../../resource/UMFile/");
define('PHP_Productsall_Thumb',Root_Path."/resource/productsallThumb/");
define('PHP_Productsall_File',Root_Path."/resource/productsallFile/");
?>