<?php 
define('Root_Path',dirname(__FILE__));
define('Project_Folder_Name',"/LLSystem");
//前台html用
define('Product_Img',"./admin/images/product/");
define('Slider_Img',"./admin/images/slider/");
define('News_Thumb',"./resource/newsThumb/");
define('News_File',"./resource/newsFile/");
define('News_Page_Size',6);
//后端php用

define('PHP_Product_Img_Path',Root_Path."/admin/images/product/");
define('PHP_Slider_Img',Root_Path."/admin/images/slider/");
define('PHP_News_Thumb',Root_Path."/resource/newsThumb/");
define('PHP_News_File',Root_Path."/resource/newsFile/");
define('PHP_News_UM_Img',"../../../resource/UMFile/");
define('PHP_productsall_Thumb',Root_Path."/resource/productsallThumb/");
define('PHP_productsall_File',Root_Path."/resource/productsallFile/");
?>